#!/usr/bin/env node
console.log('start jsnative-loader');
require('jsnative');
require('tizen-application');

var apppath = require('tizen-prelauncher').ready();
if (apppath)
  require(apppath);
else
  console.log('can\'t start loader');
